import { Protocol } from 'puppeteer-core'

export const FB_COOKIES: Protocol.Network.CookieParam[] = [
  {
    name: 'fr',
    value:
      '0CfrCmvQPHo1GG0MG.AWVd904vPmxw1m2tDuuE8lBzcJU.BkeERF.XH.AAA.0.0.BkeERF.AWXxA2oZkCI',
    domain: '.facebook.com',
    path: '/',
    expires: 1693379443.165634,
    // size: 84,
    httpOnly: true,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'xs',
    value:
      '21%3AE-CldEfeyJSQJg%3A2%3A1685602613%3A-1%3A11303%3A%3AAcWvzI4CVFVEKPNAQfCjvHOwzQ_UQekoyzWG0RfDFQ',
    domain: '.facebook.com',
    path: '/',
    expires: 1717053043.165617,
    // size: 50,
    httpOnly: true,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'datr',
    value: 'N0F4ZF3fmn5ooIVYa32WopQv',
    domain: '.facebook.com',
    path: '/',
    expires: 1717053043.683291,
    // size: 28,
    httpOnly: true,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'c_user',
    value: '100000236390565',
    domain: '.facebook.com',
    path: '/',
    expires: 1717053043.165594,
    // size: 21,
    httpOnly: false,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'wd',
    value: '400x377',
    domain: '.facebook.com',
    path: '/',
    expires: 1717053043,
    // size: 9,
    httpOnly: false,
    secure: true,
    // session: false,
    sameSite: 'Lax',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
  {
    name: 'sb',
    value: 'zwMIZK3hoow9jI0BySMHEFm7',
    domain: '.facebook.com',
    path: '/',
    expires: 1717053043.165546,
    // size: 26,
    httpOnly: true,
    secure: true,
    // session: false,
    sameSite: 'None',
    sameParty: false,
    sourceScheme: 'Secure',
    sourcePort: 443,
  },
]
