/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: 'us-east-1',
  aws_appsync_graphqlEndpoint:
    'https://lqp6v6kmkzdozb7pcrpiqkruoi.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'API_KEY',
  aws_appsync_apiKey: 'da2-hpl3eeg3qfgurjjllgzicicpiu',
  aws_cognito_identity_pool_id:
    'us-east-1:f1e9e73d-f978-4723-b1de-aa13af4b7ce0',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_RjkpVltDT',
  aws_user_pools_web_client_id: '7r44eivl034kkc0njt57efg09p',
  federationTarget: 'COGNITO_USER_AND_IDENTITY_POOLS',
  aws_user_files_s3_bucket: 'bruno-bucket83908e77-1kbjojz6gr7ho',
  aws_user_files_s3_bucket_region: 'us-east-1',
}

export default awsmobile
